In [7]:
%load_ext autoreload
%autoreload 2

In [10]:
from popper import Popper

agent = Popper(llm="gpt-4o-mini")

agent.register_data(data_path='./bio', loader_type='bio')

Data already exists, loading...

In [12]:
agent.kwargs = {"plot_agent_architecture": False}

In [14]:
agent.configure(
    alpha=0.1,
    max_num_of_tests=5,
    max_retry=3,
    time_limit=2,
    aggregate_test='E-value',
    relevance_checker=True,
    use_react_agent=True,
)

In [23]:
print(agent.data_loader.table_dict)

{'df_gtex_tissue_gene_tpm':              Description                  Tissue   Expression     Gene
0        ENSG00000186092  Adipose - Subcutaneous     0.045396    OR4F5
1        ENSG00000284733  Adipose - Subcutaneous     0.037204   OR4F29
2        ENSG00000284662  Adipose - Subcutaneous     0.023821   OR4F16
3        ENSG00000187634  Adipose - Subcutaneous     0.476230   SAMD11
4        ENSG00000188976  Adipose - Subcutaneous    52.861400    NOC2L
...                  ...                     ...          ...      ...
1007905  ENSG00000212907             Whole Blood  1234.540000  MT-ND4L
1007906  ENSG00000198886             Whole Blood  3881.600000   MT-ND4
1007907  ENSG00000198786             Whole Blood   709.967000   MT-ND5
1007908  ENSG00000198695             Whole Blood   960.291000   MT-ND6
1007909  ENSG00000198727             Whole Blood  2305.490000   MT-CYB

[1007910 rows x 4 columns], 'df_gwas_catalog':        DATE ADDED TO CATALOG  PUBMEDID FIRST AUTHOR        DATE    JOURNAL  \
0                 2018-07-30  27618447  Surendran P  2016-10-01  Nat Genet
1                 2018-07-30  27618447  Surendran P  2016-10-01  Nat Genet
2                 2018-07-30  27618447  Surendran P  2016-10-01  Nat Genet
3                 2018-07-30  27618447  Surendran P  2016-10-01  Nat Genet
4                 2018-07-30  27618447  Surendran P  2016-10-01  Nat Genet
...                      ...       ...          ...         ...        ...
622779            2023-02-09  36224396      Yengo L  2022-10-12     Nature
622780            2023-02-09  36224396      Yengo L  2022-10-12     Nature
622781            2023-02-09  36224396      Yengo L  2022-10-12     Nature
622782            2023-02-09  36224396      Yengo L  2022-10-12     Nature
622783            2023-02-09  36224396      Yengo L  2022-10-12     Nature

                                        LINK  \
0       www.ncbi.nlm.nih.gov/pubmed/27618447
1       www.ncbi.nlm.nih.gov/pubmed/27618447
2       www.ncbi.nlm.nih.gov/pubmed/27618447
3       www.ncbi.nlm.nih.gov/pubmed/27618447
4       www.ncbi.nlm.nih.gov/pubmed/27618447
...                                      ...
622779  www.ncbi.nlm.nih.gov/pubmed/36224396
622780  www.ncbi.nlm.nih.gov/pubmed/36224396
622781  www.ncbi.nlm.nih.gov/pubmed/36224396
622782  www.ncbi.nlm.nih.gov/pubmed/36224396
622783  www.ncbi.nlm.nih.gov/pubmed/36224396

                                                    STUDY  \
0       Trans-ancestry meta-analyses identify rare and...
1       Trans-ancestry meta-analyses identify rare and...
2       Trans-ancestry meta-analyses identify rare and...
3       Trans-ancestry meta-analyses identify rare and...
4       Trans-ancestry meta-analyses identify rare and...
...                                                   ...
622779  A saturated map of common genetic variants ass...
622780  A saturated map of common genetic variants ass...
622781  A saturated map of common genetic variants ass...
622782  A saturated map of common genetic variants ass...
622783  A saturated map of common genetic variants ass...

                  DISEASE/TRAIT  \
0       systolic blood pressure
1       systolic blood pressure
2       systolic blood pressure
3       systolic blood pressure
4       systolic blood pressure
...                         ...
622779                   height
622780                   height
622781                   height
622782                   height
622783                   height

                                      INITIAL SAMPLE SIZE  \
0       up to 165,276 European ancestry individuals, u...
1       up to 165,276 European ancestry individuals, u...
2       up to 165,276 European ancestry individuals, u...
3       up to 165,276 European ancestry individuals, u...
4       up to 165,276 European ancestry individuals, u...
...                                                   ...
622779  5,314,291 European ancestry, Hispanic or Latin...
622780  5,314,291 European ancestry, Hispanic or Latin...
622781  5,314,291 European ancestry, Hispanic or Latin...
622782  5,314,291 European ancestry, Hispanic or Latin...
622783  5,314,291 European ancestry, Hispanic or Latin...

                                  REPLICATION SAMPLE SIZE  ...  \
0       up to 125,713 European ancestry individuals, u...  ...
1       up to 125,713 European ancestry individuals, u...  ...
2       up to 125,713 European ancestry individuals, u...  ...
3       up to 125,713 European ancestry individuals, u...  ...
4       up to 125,713 European ancestry individuals, u...  ...
...                                                   ...  ...
622779                                                NaN  ...
622780                                                NaN  ...
622781                                                NaN  ...
622782                                                NaN  ...
622783                                                NaN  ...

                          CONTEXT INTERGENIC RISK ALLELE FREQUENCY  \
0                  intron_variant        0.0                0.5261
1                missense_variant        0.0                0.0603
2              intergenic_variant        1.0                0.4102
3                  intron_variant        1.0                0.3797
4                  intron_variant        0.0                0.7305
...                           ...        ...                   ...
622779             intron_variant        0.0                0.2499
622780         intergenic_variant        1.0                 0.196
622781  regulatory_region_variant        1.0                0.3435
622782         intergenic_variant        1.0                0.1194
622783             intron_variant        0.0                 0.157

              P-VALUE PVALUE_MLOG P-VALUE (TEXT) OR or BETA  \
0        8.000000e-09    8.096910            NaN     0.0196
1        1.000000e-07    7.000000            NaN     0.0420
2        7.000000e-23   22.154902            NaN     0.0327
3        4.000000e-08    7.397940            NaN     0.0194
4        3.000000e-07    6.522879            NaN     0.0191
...               ...         ...            ...        ...
622779   7.000000e-16   15.154902  (conditional)     0.0064
622780   1.000000e-10   10.000000  (conditional)     0.0058
622781   2.000000e-14   13.698970  (conditional)     0.0053
622782   1.000000e-10   10.000000  (conditional)     0.0063
622783  2.000000e-262  261.698970  (conditional)     0.0646

                        95% CI (TEXT)  \
0                       mmHg decrease
1                       mmHg decrease
2                       mmHg decrease
3                       mmHg decrease
4                       mmHg decrease
...                               ...
622779   [0.0048-0.008] unit increase
622780   [0.004-0.0076] unit increase
622781  [0.0039-0.0067] unit decrease
622782  [0.0043-0.0083] unit increase
622783    [0.061-0.068] unit increase

                      PLATFORM [SNPS PASSING QC]  CNV
0                              Illumina [242296]    N
1                              Illumina [242296]    N
2                              Illumina [242296]    N
3                              Illumina [242296]    N
4                              Illumina [242296]    N
...                                          ...  ...
622779  Affymetrix, Illumina [1385132] (imputed)    N
622780  Affymetrix, Illumina [1385132] (imputed)    N
622781  Affymetrix, Illumina [1385132] (imputed)    N
622782  Affymetrix, Illumina [1385132] (imputed)    N
622783  Affymetrix, Illumina [1385132] (imputed)    N

[622784 rows x 34 columns], 'df_gene_info':                gene_id    transcript_id chr  gene_start  gene_end  strand  \
0      ENSG00000228037  ENST00000424215   1     2581560   2584533       1
1      ENSG00000142611  ENST00000270722   1     3069168   3438621       1
2      ENSG00000284616  ENST00000641871   1     5301928   5307394      -1
3      ENSG00000157911  ENST00000447513   1     2403964   2413797      -1
4      ENSG00000260972  ENST00000564261   1     5492978   5494674       1
...                ...              ...  ..         ...       ...     ...
63081  ENSG00000212856  ENST00000651733   Y     6406244   6462091      -1
63082  ENSG00000147753  ENST00000715683   Y     6443345   6457906       1
63083  ENSG00000185700  ENST00000455570   Y     6470773   6473630      -1
63084  ENSG00000235895  ENST00000425857   Y     6492976   6496757      -1
63085  ENSG00000232620  ENST00000450329   Y     6520463   6520929       1

       transcript_start  transcript_end      tss  transcript_is_canonical  \
0               2581560         2584533  2581560                      1.0
1               3069203         3438621  3069203                      1.0
2               5301928         5307394  5307394                      1.0
3               2403974         2412564  2412564                      1.0
4               5492978         5494674  5492978                      1.0
...                 ...             ...      ...                      ...
63081           6411470         6462091  6462091                      1.0
63082           6443345         6457906  6443345                      1.0
63083           6470773         6473630  6473630                      1.0
63084           6492976         6496757  6496757                      1.0
63085           6520463         6520929  6520463                      1.0

      gene_name  percentage_gene_gc_content               gene_type
0           NaN                       51.11                  lncRNA
1        PRDM16                       57.58          protein_coding
2           NaN                       43.88                  lncRNA
3         PEX10                       61.52          protein_coding
4           NaN                       51.62                  lncRNA
...         ...                         ...                     ...
63081    TTTY2B                       45.86                  lncRNA
63082     TTTY7                       46.81                  lncRNA
63083    TTTY8B                       45.80                  lncRNA
63084       NaN                       32.81  unprocessed_pseudogene
63085   TSPY17P                       64.45  unprocessed_pseudogene

[63086 rows x 13 columns], 'df_genetic_interaction':          interaction_id    gene_a_id     gene_b_id experimental_system_type  \
96170            206363      YCR011C       YCL025C                  genetic
96171            206364      YCR011C       YFL031W                  genetic
96172            206365      YCR011C       YBR171W                  genetic
96173            206366      YCR011C       YLR039C                  genetic
96174            206367      YCR011C       YJR073C                  genetic
...                 ...          ...           ...                      ...
2648759         3662050  SPAC3C7.07c   SPBC1271.14                  genetic
2648760         3662051  SPAC3C7.07c   SPAC17A5.16                  genetic
2648761         3662052  SPAC3C7.07c  SPBC16H5.07c                  genetic
2648762         3662053  SPAC3C7.07c   SPAC1486.01                  genetic
2648763         3662054  SPAC3C7.07c    SPBC215.05                  genetic

               pubmed_id  organism_id_a  organism_id_b  throughput_type  \
96170    PUBMED:16269340         559292         559292  High Throughput
96171    PUBMED:16269340         559292         559292  High Throughput
96172    PUBMED:16269340         559292         559292  High Throughput
96173    PUBMED:16269340         559292         559292  High Throughput
96174    PUBMED:16269340         559292         559292  High Throughput
...                  ...            ...            ...              ...
2648759  PUBMED:32435206         284812         284812  High Throughput
2648760  PUBMED:32435206         284812         284812  High Throughput
2648761  PUBMED:32435206         284812         284812  High Throughput
2648762  PUBMED:32435206         284812         284812  High Throughput
2648763  PUBMED:32435206         284812         284812  High Throughput

        experimental_score
96170              -5.6431
96171               2.5219
96172               2.5479
96173               2.9746
96174               2.9927
...                    ...
2648759            2.07945
2648760            2.03293
2648761            2.00769
2648762            2.00647
2648763            1.99181

[736749 rows x 9 columns], 'df_genebass_synonymous_filtered':        annotation   Pvalue  Pvalue_Burden  Pvalue_SKAT  BETA_Burden  \
0      synonymous  0.72199        0.85198      0.52215     0.003470
1      synonymous  0.50108        0.34473      0.69170    -0.007786
2      synonymous  0.22191        0.13085      0.92519    -0.031094
3      synonymous  0.34181        0.76011      0.21475     0.001662
4      synonymous  0.88809        0.68727      0.69622    -0.005974
...           ...      ...            ...          ...          ...
19214  synonymous  0.81941        0.62285      0.93808     0.004301
19215  synonymous  0.71133        0.87847      0.50840    -0.000817
19216  synonymous  0.59274        0.38310      0.79610    -0.004884
19217  synonymous  0.25939        0.77989      0.17679     0.001502
19225  synonymous  0.23729        0.31356      0.14236    -0.007791

       SE_Burden          gene  \
0       0.018598        TSPAN6
1       0.008240          TNMD
2       0.020581          DPM1
3       0.005442         SCYL3
4       0.014840         FIRRM
...          ...           ...
19214   0.008745       C8orf44
19215   0.005342  C8orf44-SGK3
19216   0.005599        NPBWR1
19217   0.005374    PDCD6-AHRR
19225   0.007731          CDR1

                                       pheno_description
0           Eye problems/disorders; Macular degeneration
1           Eye problems/disorders; Macular degeneration
2           Eye problems/disorders; Macular degeneration
3           Eye problems/disorders; Macular degeneration
4           Eye problems/disorders; Macular degeneration
...                                                  ...
19214  Mean ICVF in anterior corona radiata on FA ske...
19215  Mean ICVF in anterior corona radiata on FA ske...
19216  Mean ICVF in anterior corona radiata on FA ske...
19217  Mean ICVF in anterior corona radiata on FA ske...
19225  Mean ICVF in anterior corona radiata on FA ske...

[26529562 rows x 8 columns], 'df_genebass_missense_LC_filtered':         annotation    Pvalue  Pvalue_Burden  Pvalue_SKAT  BETA_Burden  \
0      missense_LC  0.854340        0.69637     0.871350    -0.004697
1      missense_LC  0.042610        0.26621     0.029242     0.010606
2      missense_LC  0.636810        0.72674     0.469870     0.002939
3      missense_LC  0.550220        0.35235     0.721670     0.005416
4      missense_LC  0.218140        0.12994     0.471050     0.007535
...            ...       ...            ...          ...          ...
19334  missense_LC  0.835120        0.62801     0.829200     0.010957
19335  missense_LC  0.025595        0.48203     0.015419     0.010658
19337  missense_LC  0.073337        0.44562     0.042681    -0.008114
19339  missense_LC  0.599180        0.41221     0.447930     0.011252
19348  missense_LC  0.804360        0.76304     0.616240    -0.003353

       SE_Burden          gene                              pheno_description
0       0.012037        TSPAN6         Treatment/medication code; co-dydramol
1       0.009539          TNMD         Treatment/medication code; co-dydramol
2       0.008409          DPM1         Treatment/medication code; co-dydramol
3       0.005824         SCYL3         Treatment/medication code; co-dydramol
4       0.004976         FIRRM         Treatment/medication code; co-dydramol
...          ...           ...                                            ...
19334   0.022613       C8orf44  Date O48 first reported (prolonged pregnancy)
19335   0.015160  C8orf44-SGK3  Date O48 first reported (prolonged pregnancy)
19337   0.010638        NPBWR1  Date O48 first reported (prolonged pregnancy)
19339   0.013722    PDCD6-AHRR  Date O48 first reported (prolonged pregnancy)
19348   0.011122          CDR1  Date O48 first reported (prolonged pregnancy)

[26583531 rows x 8 columns], 'df_genebass_pLoF_filtered':       annotation   Pvalue  Pvalue_Burden  Pvalue_SKAT  BETA_Burden  SE_Burden  \
0           pLoF  0.59145        0.96398      0.42053    -0.000538   0.011913
1           pLoF  0.28392        0.52742      0.17438     0.007124   0.011273
2           pLoF  1.00000        0.79620      0.95334    -0.001510   0.005847
3           pLoF  0.65640        0.48874      0.70959    -0.016567   0.023931
4           pLoF  0.78310        0.65290      0.77505     0.010761   0.023927
...          ...      ...            ...          ...          ...        ...
14609       pLoF  0.26263        0.16127      0.56721    -0.017864   0.012752
14614       pLoF  0.26489        0.16899      0.47345    -0.021466   0.015606
14615       pLoF  1.00000        0.79176      0.76980     0.000930   0.003524
14616       pLoF  0.23803        0.14117      0.50194     0.021278   0.014461
14617       pLoF  0.52921            NaN          NaN          NaN        NaN

               gene                                  pheno_description
0              DPM1                   Mean L1 in fornix on FA skeleton
1             SCYL3                   Mean L1 in fornix on FA skeleton
2             FIRRM                   Mean L1 in fornix on FA skeleton
3               FGR                   Mean L1 in fornix on FA skeleton
4               CFH                   Mean L1 in fornix on FA skeleton
...             ...                                                ...
14609         HERC3  Weighted-mean ICVF in tract cingulate gyrus pa...
14614  DUS4L-BCAP29  Weighted-mean ICVF in tract cingulate gyrus pa...
14615       C8orf44  Weighted-mean ICVF in tract cingulate gyrus pa...
14616  C8orf44-SGK3  Weighted-mean ICVF in tract cingulate gyrus pa...
14617        NPBWR1  Weighted-mean ICVF in tract cingulate gyrus pa...

[24383843 rows x 8 columns], 'df_affinity_capture_ms':          interaction_id        gene_a_id        gene_b_id  \
121446           241421  ENSG00000169217  ENSG00000144028
121447           241422  ENSG00000123159  ENSG00000196586
121448           241423  ENSG00000156976  ENSG00000114867
121449           241424  ENSG00000169217  ENSG00000174231
121450           241425  ENSG00000165527  ENSG00000138095
...                 ...              ...              ...
2617126         3629874  ENSG00000163162  ENSG00000084754
2617127         3629875  ENSG00000163162  ENSG00000164070
2617128         3629876  ENSG00000163162  ENSG00000143643
2617129         3629877  ENSG00000163162  ENSG00000141959
2617130         3629878  ENSG00000163162  ENSG00000067057

        experimental_system_type        pubmed_id  organism_id_a  \
121446                  physical  PUBMED:17353931           9606
121447                  physical  PUBMED:17353931           9606
121448                  physical  PUBMED:17353931           9606
121449                  physical  PUBMED:17353931           9606
121450                  physical  PUBMED:17353931           9606
...                          ...              ...            ...
2617126                 physical  PUBMED:36610398           9606
2617127                 physical  PUBMED:36610398           9606
2617128                 physical  PUBMED:36610398           9606
2617129                 physical  PUBMED:36610398           9606
2617130                 physical  PUBMED:36610398           9606

         organism_id_b  throughput_type experimental_score
121446            9606  High Throughput                1.0
121447            9606  High Throughput              0.952
121448            9606  High Throughput              0.931
121449            9606  High Throughput              0.919
121450            9606  High Throughput              0.909
...                ...              ...                ...

In [40]:
from langchain_core.tools import tool

In [13]:

# Validate a hypothesis
results = agent.validate(hypothesis="Your hypothesis here")

# Print the results
print(results)

================================ Human Message =================================


Given a biology hypothesis "Your hypothesis here", your goal is to propose a novel falsification test given the available biology data sources.
A falsification test is a test that can potentially falsify the main hypothesis.
The outcome of the falsification test is to return a p-value that measures the evidence to falsify the main hypothesis.

Notably, the falsification test should satisfy the following property: if the main hypotheiss is null, then the falsification sub-hypothesis should also be null.

Here are the list of available data sources, and you can directly call the dataframe as it has already been loaded; no need to load from file path. Each is a pandas dataframe with columns and example rows:

df_gtex_tissue_gene_tpm:
{'Description': 'ENSG00000186092', 'Tissue': 'Adipose - Subcutaneous', 'Expression': 0.0453961, 'Gene': 'OR4F5'}

df_gwas_catalog:
{'DATE ADDED TO CATALOG': '2018-07-30', 'PUBMEDID': 27618447, 'FIRST AUTHOR': 'Surendran P', 'DATE': '2016-10-01', 'JOURNAL': 'Nat Genet', 'LINK': 'www.ncbi.nlm.nih.gov/pubmed/27618447', 'STUDY': 'Trans-ancestry meta-analyses identify rare and common variants associated with blood pressure and hypertension.', 'DISEASE/TRAIT': 'systolic blood pressure', 'INITIAL SAMPLE SIZE': 'up to 165,276 European ancestry individuals, up to 27,487 South Asian ancestry individuals', 'REPLICATION SAMPLE SIZE': 'up to 125,713 European ancestry individuals, up to 2,641 South Asian ancestry individuals, 4,632 Hispanic individuals, 22,077 African American individuals', 'REGION': '3q26.2', 'CHR_ID': '3', 'CHR_POS': '169383111', 'REPORTED GENE(S)': 'MECOM', 'MAPPED_GENE': 'MECOM', 'UPSTREAM_GENE_ID': nan, 'DOWNSTREAM_GENE_ID': nan, 'SNP_GENE_IDS': 'ENSG00000085276', 'UPSTREAM_GENE_DISTANCE': nan, 'DOWNSTREAM_GENE_DISTANCE': nan, 'STRONGEST SNP-RISK ALLELE': 'rs448378-A', 'SNPS': 'rs448378', 'MERGED': 0, 'SNP_ID_CURRENT': 448378.0, 'CONTEXT': 'intron_variant', 'INTERGENIC': 0.0, 'RISK ALLELE FREQUENCY': '0.5261', 'P-VALUE': 8e-09, 'PVALUE_MLOG': 8.096910013008056, 'P-VALUE (TEXT)': nan, 'OR or BETA': 0.0196, '95% CI (TEXT)': 'mmHg decrease', 'PLATFORM [SNPS PASSING QC]': 'Illumina [242296]', 'CNV': 'N'}

df_gene_info:
{'gene_id': 'ENSG00000228037', 'transcript_id': 'ENST00000424215', 'chr': '1', 'gene_start': 2581560, 'gene_end': 2584533, 'strand': 1, 'transcript_start': 2581560, 'transcript_end': 2584533, 'tss': 2581560, 'transcript_is_canonical': 1.0, 'gene_name': nan, 'percentage_gene_gc_content': 51.11, 'gene_type': 'lncRNA'}

df_genetic_interaction:
{'interaction_id': 206363, 'gene_a_id': 'YCR011C', 'gene_b_id': 'YCL025C', 'experimental_system_type': 'genetic', 'pubmed_id': 'PUBMED:16269340', 'organism_id_a': 559292, 'organism_id_b': 559292, 'throughput_type': 'High Throughput', 'experimental_score': '-5.6431'}

df_genebass_synonymous_filtered:
{'annotation': 'synonymous', 'Pvalue': 0.72199, 'Pvalue_Burden': 0.85198, 'Pvalue_SKAT': 0.52215, 'BETA_Burden': 0.0034703, 'SE_Burden': 0.018598, 'gene': 'TSPAN6', 'pheno_description': 'Eye problems/disorders; Macular degeneration'}

df_genebass_missense_LC_filtered:
{'annotation': 'missense_LC', 'Pvalue': 0.85434, 'Pvalue_Burden': 0.69637, 'Pvalue_SKAT': 0.87135, 'BETA_Burden': -0.0046974, 'SE_Burden': 0.012037, 'gene': 'TSPAN6', 'pheno_description': 'Treatment/medication code; co-dydramol'}

df_genebass_pLoF_filtered:
{'annotation': 'pLoF', 'Pvalue': 0.59145, 'Pvalue_Burden': 0.96398, 'Pvalue_SKAT': 0.42053, 'BETA_Burden': -0.00053797, 'SE_Burden': 0.011913, 'gene': 'DPM1', 'pheno_description': 'Mean L1 in fornix on FA skeleton'}

df_affinity_capture_ms:
{'interaction_id': 241421, 'gene_a_id': 'ENSG00000169217', 'gene_b_id': 'ENSG00000144028', 'experimental_system_type': 'physical', 'pubmed_id': 'PUBMED:17353931', 'organism_id_a': 9606, 'organism_id_b': 9606, 'throughput_type': 'High Throughput', 'experimental_score': '1.0'}

df_two_hybrid:
{'interaction_id': 269293, 'gene_a_id': 'ENSG00000114395', 'gene_b_id': 'ENSG00000109103', 'experimental_system_type': 'physical', 'pubmed_id': 'PUBMED:16169070', 'organism_id_a': 9606, 'organism_id_b': 9606, 'throughput_type': 'High Throughput', 'experimental_score': '1.0'}

df_synthetic_growth_defect:
{'interaction_id': 299191, 'gene_a_id': 'SPBC30D10.04', 'gene_b_id': 'SPAC14C4.13', 'experimental_system_type': 'genetic', 'pubmed_id': 'PUBMED:18931302', 'organism_id_a': 284812, 'organism_id_b': 284812, 'throughput_type': 'High Throughput', 'experimental_score': '-366.0'}

df_affinity_capture_rna:
{'interaction_id': 637589, 'gene_a_id': 'YDR515W', 'gene_b_id': 'YAL030W', 'experimental_system_type': 'physical', 'pubmed_id': 'PUBMED:22271760', 'organism_id_a': 559292, 'organism_id_b': 559292, 'throughput_type': 'High Throughput', 'experimental_score': '0.736666667'}

df_co_fractionation:
{'interaction_id': 740709, 'gene_a_id': 'ENSG00000160201', 'gene_b_id': 'ENSG00000063244', 'experimental_system_type': 'physical', 'pubmed_id': 'PUBMED:22939629', 'organism_id_a': 9606, 'organism_id_b': 9606, 'throughput_type': 'High Throughput', 'experimental_score': '0.874'}

df_synthetic_lethality:
{'interaction_id': 818564, 'gene_a_id': 'YLR418C', 'gene_b_id': 'YLR103C', 'experimental_system_type': 'genetic', 'pubmed_id': 'PUBMED:23390603', 'organism_id_a': 559292, 'organism_id_b': 559292, 'throughput_type': 'High Throughput|Low Throughput', 'experimental_score': '4.75e-06'}

df_dosage_growth_defect:
{'interaction_id': 908565, 'gene_a_id': 'YBL009W', 'gene_b_id': 'YPR058W', 'experimental_system_type': 'genetic', 'pubmed_id': 'PUBMED:22282571', 'organism_id_a': 559292, 'organism_id_b': 559292, 'throughput_type': 'High Throughput', 'experimental_score': '-0.504'}

df_proximity_label_ms:
{'interaction_id': 913336, 'gene_a_id': 'ENSG00000206560', 'gene_b_id': 'ENSG00000103194', 'experimental_system_type': 'physical', 'pubmed_id': 'PUBMED:24255178', 'organism_id_a': 9606, 'organism_id_b': 9606, 'throughput_type': 'High Throughput', 'experimental_score': '1.0'}

df_synthetic_rescue:
{'interaction_id': 986367, 'gene_a_id': 'YJR017C', 'gene_b_id': 'YHR114W', 'experimental_system_type': 'genetic', 'pubmed_id': 'PUBMED:24470217', 'organism_id_a': 559292, 'organism_id_b': 559292, 'throughput_type': 'High Throughput', 'experimental_score': '-0.2'}

df_reconstituted_complex:
{'interaction_id': 2841862, 'gene_a_id': 'ENSG00000169083', 'gene_b_id': 'ENSG00000097007', 'experimental_system_type': 'physical', 'pubmed_id': 'PUBMED:24728074', 'organism_id_a': 9606, 'organism_id_b': 9606, 'throughput_type': 'High Throughput', 'experimental_score': '2.13'}

df_eqtl_ukbb:
{'rs_id': 'rs111972115', 'gene_id': 'ENSG00000134250', 'cell_type_name': 'CEDAR-MONOCYTE_CD14', 'qtl_score': 4.851273983601853, 'gene_name': 'NOTCH2'}

df_pqtl_ukbb:
{'rs_id': 'rs41265213', 'gene_id': 'ENSG00000160712', 'cell_type_name': 'SCALLOP_2020-UBERON_0001969', 'qtl_score': 5.13715334001706, 'gene_name': 'IL6R'}

df_sqtl_ukbb:
{'rs_id': 'rs12756687', 'gene_id': 'ENSG00000265491', 'cell_type_name': 'GTEx-sQTL-Brain_Caudate_basal_ganglia', 'qtl_score': 3.19846622732464, 'gene_name': 'RNF115'}

df_variant_table:
{'RS': 'rs116587930', 'ID': '1:727841_G_A', 'CHR': 1, 'POS': 727841, 'A1': 'G', 'A2': 'A', 'MAF': 0.0507035}

df_trait:
{'pheno_name': '120_1', 'description': 'Birth weight known; Yes - pounds and ounces'}



For the final test, return
(1) Name: name of the test
(2) Test description: be clear and concise. Describe the falsification outcomes.
(3) Null sub-hypothesis h_0: what is the statistical null sub-hypothesis does this falsification test aim to test?
(4) Alternate sub-hypothesis h_1: what is the statistical alternative sub-hypothesis does this falsification test aim to test?

Here are the falsification tests that you've created in the previous rounds and their corresponding test results:

"""
No Implemented Falsification Test Yet.
"""

You may use these information to formulate your next subhypothesis and falsification test, but make sure the proposed falsification test is non-redundant with any of the existing tests.

The proposed test should also avoid these failed falsification tests in the previous rounds:

"""
[]
"""

A good falsification test should serve as a strong evidence for the main hypothesis. However, make sure it is answerable with the given available data sources.
You should aim to maximize the implication strength of the proposed falsification test using the relevant parts of the provided data.

----
First produce an initial falsification test proposal.

Then, in each round i, you will do the following:
(1) critic: ask if the main hypothesis is null, is this test also null? be rigorous. this is super important, otherwise, the test is invalid. Is it redundant on capabilities with existing tests? Is it overlapping with failed tests? Can this be answered and implemented based on the given data?
(2) reflect: how to improve this test definition.

If you think the test definition is good enough, return the final test definition to the user.
If not, either refine the test definition that is better than the previous one or propose a new test definition, then go to the next round.

================================== Ai Message ==================================

### Initial Falsification Test Proposal

(1) **Name:** Gene Expression Association with Trait Variation

(2) **Test Description:** This test will evaluate the association between gene expression levels of specific genes in relevant tissues and the variation in a biological trait, such as blood pressure. By analyzing gene expression data from the GTEx dataset and correlating it with genetic variants associated with the trait from the GWAS catalog, we can assess whether the null hypothesis holds true. If the expression of a gene significantly correlates with the trait variation, it may provide evidence against the null hypothesis.

(3) **Null Sub-Hypothesis h_0:** There is no significant association between the expression levels of the selected genes and the variation in the biological trait (e.g., blood pressure). This implies that the main hypothesis is also null.

(4) **Alternate Sub-Hypothesis h_1:** There is a significant association between the expression levels of the selected genes and the variation in the biological trait (e.g., blood pressure).

---

### Critic

1. **Null Hypothesis Validity:** If the main hypothesis is null (i.e., there is no relationship between gene expression and the trait), then the sub-hypothesis h_0 correctly states that there is no significant association between gene expression and trait variation. Thus, this test is valid in that context.

2. **Redundancy and Overlap:** The proposed test does not overlap with any existing tests or failed tests since it combines gene expression data with trait associations, which has not been tested before.

3. **Data Implementation:** The data sources available (df_gtex_tissue_gene_tpm and df_gwas_catalog) allow for this test to be conducted, as they provide the necessary gene expression and trait association information.

### Reflect

To improve the test definition, we could specify a particular gene or set of genes of interest related to the trait in question, ensuring that the test is focused and manageable. Additionally, we could define a statistical method for assessing the association (e.g., linear regression or correlation analysis) to enhance clarity.

---

### Refined Falsification Test Proposal

(1) **Name:** Gene Expression and Blood Pressure Association Test

(2) **Test Description:** This test will evaluate the association between expression levels of genes identified in the GWAS catalog related to blood pressure and their expression levels in adipose tissue from the GTEx dataset. We will conduct a linear regression analysis where the dependent variable is blood pressure variation (measured through associated genetic variants) and the independent variable is gene expression. A significant p-value will suggest a rejection of the null hypothesis.

(3) **Null Sub-Hypothesis h_0:** There is no significant association between the expression levels of selected genes (linked to blood pressure variations) and the variations in blood pressure.

(4) **Alternate Sub-Hypothesis h_1:** There is a significant association between the expression levels of selected genes (linked to blood pressure variations) and the variations in blood pressure.

---

If you find this refined proposal satisfactory, I will finalize it. If not, I will continue to improve the definition.

KeyboardInterrupt:

In [31]:
import pickle

with open('bio/bio_database/co_fractionation.pkl', 'rb') as file:
    data = pickle.load(file)

data

,interaction_id,gene_a_id,gene_b_id,experimental_system_type,pubmed_id,organism_id_a,organism_id_b,throughput_type,experimental_score
503979,740709,ENSG00000160201,ENSG00000063244,physical,PUBMED:22939629,9606,9606,High Throughput,0.874
503980,740710,ENSG00000100764,ENSG00000175166,physical,PUBMED:22939629,9606,9606,High Throughput,1.0
503981,740711,ENSG00000164754,ENSG00000072501,physical,PUBMED:22939629,9606,9606,High Throughput,1.0
503982,740712,ENSG00000106305,ENSG00000065427,physical,PUBMED:22939629,9606,9606,High Throughput,1.0
503983,740713,ENSG00000073111,ENSG00000076003,physical,PUBMED:22939629,9606,9606,High Throughput,0.998
...,...,...,...,...,...,...,...,...,...
2021702,2931942,NaN,AT3G46040,physical,PUBMED:32191846,3702,3702,High Throughput,0.510262515
2021703,2931943,NaN,AT2G39590,physical,PUBMED:32191846,3702,3702,High Throughput,0.510262515
2021704,2931944,NaN,AT1G07770,physical,PUBMED:32191846,3702,3702,High Throughput,0.510262515
2021705,2931945,NaN,NaN,physical,PUBMED:32191846,3702,3702,High Throughput,0.5091443
2021706,2931946,AT2G34640,NaN,physical,PUBMED:32191846,3702,3702,High Throughput,0.509048507

In [35]:
import json
import pandas as pd

with open('data/Monogenic_Disease_Identification.json', 'r') as file:
    data = json.load(file)

In [36]:
data

{'subgraph_id': 'fbb307af08be43318a8a0e0183ac3639cb23295e127a05f6e02ac28327a5245c',
 'graph_data': {'nodes': {'Monogenic Disease Identification': {'sources': [{'relation': 'leads to discovery of',
      'triplet_id': 2371492696656},
     {'relation': 'can influence', 'triplet_id': 2371555719936}]},
   'Autoimmune Disease Susceptibility': {'sources': [{'relation': 'are often associated with',
      'triplet_id': 2371492164240},
     {'relation': 'is influenced by', 'triplet_id': 2371555718880},
     {'relation': 'is influenced by', 'triplet_id': 2371555717248},
     {'relation': 'can affect', 'triplet_id': 2371555716864}]},
   'Extracellular Matrix (ECM) in Synovial Tissue': {'sources': [{'relation': 'degrade components of',
      'triplet_id': 2371555719552},
     {'relation': 'is remolded by', 'triplet_id': 2371555719792},
     {'relation': 'is influenced by', 'triplet_id': 2371555717248},
     {'relation': 'is affected by', 'triplet_id': 2371555720416}]},
   'Regulatory T Cell Function': {'sources': [{'relation': 'interact with',
      'triplet_id': 2371555708512},
     {'relation': 'affects', 'triplet_id': 2371555721088},
     {'relation': 'can influence', 'triplet_id': 2371555718304},
     {'relation': 'is affected by', 'triplet_id': 2371555720416},
     {'relation': 'can influence', 'triplet_id': 2371555718400}]},
   'Synovial Inflammation in Rheumatoid Arthritis': {'sources': [{'relation': 'affects',
      'triplet_id': 2371555721088},
     {'relation': 'is associated with increased levels of',
      'triplet_id': 2371555716960},
     {'relation': 'can affect', 'triplet_id': 2371555716432}]},
   'Genetic Mutation Hotspots': {'sources': [{'relation': 'leads to discovery of',
      'triplet_id': 2371492696656},
     {'relation': 'are often associated with', 'triplet_id': 2371492164240},
     {'relation': 'can modulate', 'triplet_id': 2371555718352},
     {'relation': 'can influence', 'triplet_id': 2371555718544}]},
   'Cytokine Production Profiles': {'sources': [{'relation': 'modulate expression of',
      'triplet_id': 2371555718928},
     {'relation': 'interact with', 'triplet_id': 2371555708512},
     {'relation': 'can modulate', 'triplet_id': 2371555720704},
     {'relation': 'can influence', 'triplet_id': 2371555719936}]},
   'HLA Class II Gene Variants': {'sources': [{'relation': 'is influenced by',
      'triplet_id': 2371555718880},
     {'relation': 'modulate expression of', 'triplet_id': 2371555718928},
     {'relation': 'can affect', 'triplet_id': 2371555716432}]},
   'Fibroblast-like Synoviocytes (FLS)': {'sources': [{'relation': 'is remolded by',
      'triplet_id': 2371555719792},
     {'relation': 'can influence', 'triplet_id': 2371555718304},
     {'relation': 'can modulate', 'triplet_id': 2371555720704}]},
   'Tumor Necrosis Factor-alpha (TNF-α)': {'sources': [{'relation': 'is associated with increased levels of',
      'triplet_id': 2371555716960},
     {'relation': 'stimulates the expression of', 'triplet_id': 2371555718448},
     {'relation': 'can modulate', 'triplet_id': 2371555718352},
     {'relation': 'can affect', 'triplet_id': 2371555716864}]},
   'Matrix Metalloproteinases (MMPs)': {'sources': [{'relation': 'stimulates the expression of',
      'triplet_id': 2371555718448},
     {'relation': 'degrade components of', 'triplet_id': 2371555719552},
     {'relation': 'can influence', 'triplet_id': 2371555718544},
     {'relation': 'can influence', 'triplet_id': 2371555718400}]}},
  'edges': [{'source': 'Monogenic Disease Identification',
    'target': 'Genetic Mutation Hotspots',
    'relation': 'leads to discovery of',
    'sources': [{'relation': 'leads to discovery of',
      'triplet_id': 2371492696656}]},
   {'source': 'Autoimmune Disease Susceptibility',
    'target': 'HLA Class II Gene Variants',
    'relation': 'is influenced by',
    'sources': [{'relation': 'is influenced by',
      'triplet_id': 2371555718880}]},
   {'source': 'Autoimmune Disease Susceptibility',
    'target': 'Tumor Necrosis Factor-alpha (TNF-α)',
    'relation': 'can affect',
    'sources': [{'relation': 'can affect', 'triplet_id': 2371555716864}]},
   {'source': 'Extracellular Matrix (ECM) in Synovial Tissue',
    'target': 'Fibroblast-like Synoviocytes (FLS)',
    'relation': 'is remolded by',
    'sources': [{'relation': 'is remolded by', 'triplet_id': 2371555719792}]},
   {'source': 'Extracellular Matrix (ECM) in Synovial Tissue',
    'target': 'Autoimmune Disease Susceptibility',
    'relation': 'is influenced by',
    'sources': [{'relation': 'is influenced by',
      'triplet_id': 2371555717248}]},
   {'source': 'Extracellular Matrix (ECM) in Synovial Tissue',
    'target': 'Regulatory T Cell Function',
    'relation': 'is affected by',
    'sources': [{'relation': 'is affected by', 'triplet_id': 2371555720416}]},
   {'source': 'Regulatory T Cell Function',
    'target': 'Synovial Inflammation in Rheumatoid Arthritis',
    'relation': 'affects',
    'sources': [{'relation': 'affects', 'triplet_id': 2371555721088}]},
   {'source': 'Regulatory T Cell Function',
    'target': 'Fibroblast-like Synoviocytes (FLS)',
    'relation': 'can influence',
    'sources': [{'relation': 'can influence', 'triplet_id': 2371555718304}]},
   {'source': 'Synovial Inflammation in Rheumatoid Arthritis',
    'target': 'Tumor Necrosis Factor-alpha (TNF-α)',
    'relation': 'is associated with increased levels of',
    'sources': [{'relation': 'is associated with increased levels of',
      'triplet_id': 2371555716960}]},
   {'source': 'Synovial Inflammation in Rheumatoid Arthritis',
    'target': 'HLA Class II Gene Variants',
    'relation': 'can affect',
    'sources': [{'relation': 'can affect', 'triplet_id': 2371555716432}]},
   {'source': 'Genetic Mutation Hotspots',
    'target': 'Autoimmune Disease Susceptibility',
    'relation': 'are often associated with',
    'sources': [{'relation': 'are often associated with',
      'triplet_id': 2371492164240}]},
   {'source': 'Genetic Mutation Hotspots',
    'target': 'Matrix Metalloproteinases (MMPs)',
    'relation': 'can influence',
    'sources': [{'relation': 'can influence', 'triplet_id': 2371555718544}]},
   {'source': 'Cytokine Production Profiles',
    'target': 'Regulatory T Cell Function',
    'relation': 'interact with',
    'sources': [{'relation': 'interact with', 'triplet_id': 2371555708512}]},
   {'source': 'Cytokine Production Profiles',
    'target': 'Monogenic Disease Identification',
    'relation': 'can influence',
    'sources': [{'relation': 'can influence', 'triplet_id': 2371555719936}]},
   {'source': 'HLA Class II Gene Variants',
    'target': 'Cytokine Production Profiles',
    'relation': 'modulate expression of',
    'sources': [{'relation': 'modulate expression of',
      'triplet_id': 2371555718928}]},
   {'source': 'Fibroblast-like Synoviocytes (FLS)',
    'target': 'Cytokine Production Profiles',
    'relation': 'can modulate',
    'sources': [{'relation': 'can modulate', 'triplet_id': 2371555720704}]},
   {'source': 'Tumor Necrosis Factor-alpha (TNF-α)',
    'target': 'Matrix Metalloproteinases (MMPs)',
    'relation': 'stimulates the expression of',
    'sources': [{'relation': 'stimulates the expression of',
      'triplet_id': 2371555718448}]},
   {'source': 'Tumor Necrosis Factor-alpha (TNF-α)',
    'target': 'Genetic Mutation Hotspots',
    'relation': 'can modulate',
    'sources': [{'relation': 'can modulate', 'triplet_id': 2371555718352}]},
   {'source': 'Matrix Metalloproteinases (MMPs)',
    'target': 'Extracellular Matrix (ECM) in Synovial Tissue',
    'relation': 'degrade components of',
    'sources': [{'relation': 'degrade components of',
      'triplet_id': 2371555719552}]},
   {'source': 'Matrix Metalloproteinases (MMPs)',
    'target': 'Regulatory T Cell Function',
    'relation': 'can influence',
    'sources': [{'relation': 'can influence', 'triplet_id': 2371555718400}]}]},
 'graph_stats': {'node_count': 11, 'edge_count': 20, 'path_length': 11},
 'start_node': 'Monogenic Disease Identification',
 'end_node': 'Fibroblast-like Synoviocytes (FLS)',
 'path_nodes': ['Monogenic Disease Identification',
  'Genetic Mutation Hotspots',
  'Autoimmune Disease Susceptibility',
  'HLA Class II Gene Variants',
  'Cytokine Production Profiles',
  'Regulatory T Cell Function',
  'Synovial Inflammation in Rheumatoid Arthritis',
  'Tumor Necrosis Factor-alpha (TNF-α)',
  'Matrix Metalloproteinases (MMPs)',
  'Extracellular Matrix (ECM) in Synovial Tissue',
  'Fibroblast-like Synoviocytes (FLS)'],
 'path_edges': [{'source': 'Monogenic Disease Identification',
   'target': 'Genetic Mutation Hotspots',
   'relation': 'leads to discovery of'},
  {'source': 'Genetic Mutation Hotspots',
   'target': 'Autoimmune Disease Susceptibility',
   'relation': 'are often associated with'},
  {'source': 'Autoimmune Disease Susceptibility',
   'target': 'HLA Class II Gene Variants',
   'relation': 'is influenced by'},
  {'source': 'HLA Class II Gene Variants',
   'target': 'Cytokine Production Profiles',
   'relation': 'modulate expression of'},
  {'source': 'Cytokine Production Profiles',
   'target': 'Regulatory T Cell Function',
   'relation': 'interact with'},
  {'source': 'Regulatory T Cell Function',
   'target': 'Synovial Inflammation in Rheumatoid Arthritis',
   'relation': 'affects'},
  {'source': 'Synovial Inflammation in Rheumatoid Arthritis',
   'target': 'Tumor Necrosis Factor-alpha (TNF-α)',
   'relation': 'is associated with increased levels of'},
  {'source': 'Tumor Necrosis Factor-alpha (TNF-α)',
   'target': 'Matrix Metalloproteinases (MMPs)',
   'relation': 'stimulates the expression of'},
  {'source': 'Matrix Metalloproteinases (MMPs)',
   'target': 'Extracellular Matrix (ECM) in Synovial Tissue',
   'relation': 'degrade components of'},
  {'source': 'Extracellular Matrix (ECM) in Synovial Tissue',
   'target': 'Fibroblast-like Synoviocytes (FLS)',
   'relation': 'is remolded by'}],
 'context': None,
 'path_score': None,
 'path_score_justification': None,
 'original_graph_metadata': {'node_count': 11, 'edge_count': 20},
 'config': {}}

In [ ]:
import pandas as pd
import json

# Load the JSON data
with open('data/Methotrexate__MTX_.json', 'r') as f:
    data = json.load(f)

# Create nodes DataFrame
nodes_data = []
for node_name, node_info in data['graph_data']['nodes'].items():
    nodes_data.append({
        'node_id': node_name,
        'source_count': len(node_info['sources'])
    })
    
nodes_df = pd.DataFrame(nodes_data)

# Create edges DataFrame
edges_data = []
for edge in data['graph_data']['edges']:
    edges_data.append({
        'source': edge['source'],
        'target': edge['target'],
        'relation': edge['relation'],
        'source_count': len(edge['sources'])
    })
    
edges_df = pd.DataFrame(edges_data)

# Create path DataFrame
path_data = []
for i in range(len(data['path_edges'])):
    path_data.append({
        'step': i+1,
        'source': data['path_edges'][i]['source'],
        'relation': data['path_edges'][i]['relation'],
        'target': data['path_edges'][i]['target']
    })
    
path_df = pd.DataFrame(path_data)

# Print the DataFrames
# print("Nodes DataFrame:")
# print(nodes_df)

# print("\nEdges DataFrame:")
# print(edges_df)

print("\nPath DataFrame:")
print(path_df)

Path DataFrame:
    step                                             source  \
0      1                                 Methotrexate (MTX)
1      2                     Dihydrofolate reductase (DHFR)
2      3                             Tetrahydrofolate (THF)
3      4                                 Purine nucleotides
4      5                                        DNA and RNA
5      6                                           Proteins
6      7                                          Cytokines
7      8                                    Immune response
8      9                          Rheumatoid arthritis (RA)
9     10                               Interleukin-6 (IL-6)
10    11                              IL-6 receptor (IL-6R)
11    12                                 Janus kinase (JAK)
12    13  Signal Transducer and Activator of Transcripti...

                                      relation  \
0                                     inhibits
1   is an enzyme involved in the production of
2            is a cofactor in the synthesis of
3            are involved in the production of
4                                       encode
5                                      include
6    play a critical role in the regulation of
7                       can be dysregulated in
8        is associated with elevated levels of
9                          signals through the
10                                   activates
11                              phosphorylates
12                    induce the expression of

                                               target
0                      Dihydrofolate reductase (DHFR)
1                              Tetrahydrofolate (THF)
2                                  Purine nucleotides
3                                         DNA and RNA
4                                            Proteins
5                                           Cytokines
6                                     Immune response
7                           Rheumatoid arthritis (RA)
8                                Interleukin-6 (IL-6)
9                               IL-6 receptor (IL-6R)
10                                 Janus kinase (JAK)
11  Signal Transducer and Activator of Transcripti...
12                        Acute phase proteins (APPs)

In [39]:
path_df

,step,source,relation,target
0,1,Methotrexate (MTX),inhibits,Dihydrofolate reductase (DHFR)
1,2,Dihydrofolate reductase (DHFR),is an enzyme involved in the production of,Tetrahydrofolate (THF)
2,3,Tetrahydrofolate (THF),is a cofactor in the synthesis of,Purine nucleotides
3,4,Purine nucleotides,are involved in the production of,DNA and RNA
4,5,DNA and RNA,encode,Proteins
5,6,Proteins,include,Cytokines
6,7,Cytokines,play a critical role in the regulation of,Immune response
7,8,Immune response,can be dysregulated in,Rheumatoid arthritis (RA)
8,9,Rheumatoid arthritis (RA),is associated with elevated levels of,Interleukin-6 (IL-6)
9,10,Interleukin-6 (IL-6),signals through the,IL-6 receptor (IL-6R)
10,11,IL-6 receptor (IL-6R),activates,Janus kinase (JAK)
11,12,Janus kinase (JAK),phosphorylates,Signal Transducer and Activator of Transcripti...
12,13,Signal Transducer and Activator of Transcripti...,induce the expression of,Acute phase proteins (APPs)